# Generated by Django 3.0.7 on 2020-06-22 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('seminuevos', '0002_auto_20200621_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_meli', models.CharField(max_length=25)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.CharField(max_length=25)),
                ('listing_type', models.CharField(max_length=25)),
                ('id_seminuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminuevos.Seminuevo')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.Sucursal')),
            ],
        ),
    ]
