# Generated by Django 3.0.7 on 2020-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ag', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('meli_token', models.CharField(blank=True, max_length=100, null=True)),
                ('meli_refresh_token', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_token_date', models.CharField(blank=True, max_length=15, null=True)),
                ('last_token_update', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
