# Generated by Django 3.0.7 on 2020-06-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminuevo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=20)),
                ('num_inv1', models.IntegerField()),
                ('num_inv2', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=30)),
                ('color_ext', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('kilometraje', models.IntegerField()),
                ('transmision', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('extra', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('combustible', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('puertas', models.IntegerField()),
            ],
        ),
    ]
