# Generated by Django 3.0.7 on 2020-06-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminuevos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminuevo',
            name='extra',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
